### ISSUE TITLE
Retain cycle

### ISSUE THREAD

**Issue by DenTelezhkin** [jivadevoe/NSTimer-Blocks#3]
Hi, there's a problem with current implementation, i'm not sure how to get over it.

Using NSTimer itself as a target causes retain cycle, since NSTimer retains target. I added following dealloc to the category:

-(void)dealloc {
    NSLog(@"timer dealloced");
    [super dealloc];
}

And started the timer:
[NSTimer scheduledTimerWithTimeInterval:1 block:^{
      NSLog(@"timer fired");
    } repeats:NO
     ];

Output in console was as following:

timer fired

Which means that NSTimer was never released.

**Comment by MichaelSiddi** [comment]
I found a problem in scheduledTimerRepeats:withTimeInterval:andBlock: when you are not using ARC. 
the 
 block =  [copy block];
should be 
 block = [[copy block] autorelease];

it seems that with this modification the retain cycle is "fixed"...

**Comment by DenTelezhkin** [comment]
This actually doesn't fix the problem. Block is released two lines below that line.

The problem is that when you call scheduledTimerWithTimeInterval:target:selector:userInfo:repeats:, NSTimer implementation retains it's delegate, in this case NSTimer itself. Which causes a retain cycle, because NSTimer strongly captures block in userInfo property, and block strongly captures NSTimer itself, so they are never released.

And, unfortunately, userInfo property is readonly, so we can do nothing about it. The only viable option seems to use associatedObjects to store block, and after it is fired, clean the block, and invalidate the timer. Invalidate also need to be reimplemented, so when invalidate is called on NSTimer, we could clean out the block.

But this seems to be overcomplicated for small NSTimer category. I wonder, if there's better way.

**Comment by MichaelSiddi** [comment]
Woops... sorry.. 
I answered to this one because in my code (maybe modified by someone else in my team :() there was no [release] after the copy.. so I jumped directly to the issues tab because of a retain problem without look at the original code.. 
thank you for the answer and for the solutions! 
I think i'll jump back to old NSTimer with selectors :D

**Comment by jivadevoe** [comment]
Actually... I'm pretty sure you're both incorrect.
1. You cannot implement dealloc in a category.  If you do, no instance of that class will be deallocated properly.  Never ever do that.  (Actually, you should never implement any method that exists on the class which you are implementing the category on.)
2. Once scheduled, the timer is retained by the runloop until it completes... Then it is released.
3. Although the target object (in this case, the timer itself) is retained by the timer, it is released when the timer is invalidated, which happens when it completes.
4. The block does not strongly capture NSTimer unless you are referencing the timer variable in your block that you're passing in at the point where the block is declared. And even in that case, you could prefix your timer variable with __weak to ensure that it doesn't capture it strongly.

NSTimer is a class cluster, so it's difficult to implement a dealloc method on a subclass to determine exactly when the object gets released. 

You could probably fire up instruments, and look to see if the timer is actually leaking. I'm pretty sure that if you don't capture the timer in your block, however, you should be OK.  I won't be offended if you can prove me wrong.

**Comment by DenTelezhkin** [comment]
You are correct, sorry.

This can be tested in a following way:
1. Create some test object
2. Call NSLog(@"%@",[object description]) in timer block, so that timer retained test object.
3. Test object gets released after timer fires, which means that timer no longer holds to object, and timer is also released.

Thanks for your comments!
